version: '3.8'

networks:
  geo_default:
    external:
      name: geo_default

services:
  api:
    deploy:
      resources:
        limits:
          memory: 8192M
        reservations:
          memory: 8192M
    container_name: statistics-api
    build:
      context: ./api
      dockerfile: Dockerfile
      target: production
    env_file:
      - ./api/.env
    ports:
      - $PORT:$PORT_DEV
    volumes:
      - ./api/:/usr/src/app
    networks:
      - geo_default
