version: '3.8'

services:
  api:
    container_name: sru-statistics-api
    build:
      context: ./api
      dockerfile: Dockerfile
      target: production
    env_file:
      - ./api/.env
    ports:
      - $PORT:$PORT_DEV
    volumes:
      - ./api/:/usr/src/app

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./api/redis:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - ./api/redis/data/redisinsight:/db

networks:
  api:
    driver: geo_default
  redis:
    driver: geo_default
  redisinsight:
    driver: geo_default
  mongodb:
    driver: geo_default
